### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by mredwin1** [mredwin1/DivisionManagementSystem#14]
### To-Do

- [ ] Improve the project description
- [ ] Add installation instructions
- [ ] Add a features section
- [ ] Add license
- [ ] Add a changelog?

There might be more to add but this is a good start.
